project:
  type: website
  output-dir: docs

website:
  title: Breanna Nguyá»…n
  favicon: favicon.png
  navbar:
    right:
      - text: "Home"
        file: index.qmd
        icon: "house-door"
      - text: "Projects"
        file: projects.qmd
        icon: "book"
      - text: "Personal"
        file: personal.qmd
        icon: "person-circle"
      - text: "Contact"
        file: contact.qmd
        icon: "mailbox"

format:
  html:
    theme: flatly
    toc: true
    smooth-scroll: true